version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pawfectradar_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pawfectradar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pawfectradar-network

  redis:
    image: redis:7-alpine
    container_name: pawfectradar_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - pawfectradar-network

volumes:
  postgres_data:

networks:
  pawfectradar-network:
    driver: bridge
