services:
  db:
    image: postgres:15-alpine
    container_name: pawfect_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pawfectradar_dev
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 40
    networks:
      - pawfectsitters-network

  db_test:
    image: postgres:15-alpine
    container_name: pawfect_db_test
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pawfectradar_test
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 40
    networks:
      - pawfectsitters-network

  redis:
    image: redis:7-alpine
    container_name: pawfect_redis
    command: ["redis-server","--save","","--appendonly","no"]
    ports:
      - "6379:6379"
    networks:
      - pawfectsitters-network

volumes:
  db_data:

networks:
  pawfectsitters-network:
    name: pawfectsitters-network
    driver: bridge
